### ISSUE TITLE
vex2difx  converts the hostname to lowercase

### ISSUE THREAD

**Issue by billchen0001** [difx/difx#63] opened 2024-11-02 09:44 UTC
We just found that vex2difx (DiFX 2.6.2) converts the hostname in the machines parameter to lowercase, such as changing R200 to r200. Since Linux is case-sensitive, this prevents further calculation from proceeding.

Regards,
Bill

**Comment by walterfb** [comment] 2024-11-04 03:42
Hi Bill,

Thanks for the report.  Probably the fix is simple.  When it is implemented it will be made for the development branch.  I don't think any effort will be made to maintain the 2.6 series at this point.  If you have already found a fix for this, I suggest you make a new branch based on the current "dev" branch and then issue a pull request.

Cheers,

Walter

**Comment by XhrisPhillips** [comment] 2024-11-04 03:46
Hi bill,

My understanding is that hostnames are meant to be case insensitive (Linux or not is irrelevant). What actually is breaking?

Regards
Chris

On 2 Nov 2024, at 20:45, billchen0001 ***@***.***> wrote:



We just found that vex2difx (DiFX 2.6.2) converts the hostname in the machines parameter to lowercase, such as changing R200 to r200. Since Linux is case-sensitive, this prevents further calculation from proceeding.

Regards,
Bill

**Comment by billchen0001** [comment] 2024-11-04 16:28
Hi Walter and Chris,
I think the hostname in Linux is case-sensitive, especially when using mpi with a machinefile in DiFX for parsing. Since we usually write the machine name to IP address resolution into the /etc/hosts file, the problem I encountered is that our machine name is R200, but vex2difx generates an mpi machinefile with r200. R200 and r200 as machine names would be considered two different machines, so I couldn't run the subsequent mpifxcorr. I have already solved this problem simply by: 1. Adding an r200 to IP address resolution to /etc/hosts, 2. Manually modifying the resolution records in xxx.machines. I can issue a PR to fix it.
I believe that DiFX itself does not involve case sensitivity issues with machine names, but MPI and Linux do distinguish between cases. Additionally, I am integrating DiFX into the HPC scheduling system, which also distinguishes between cases.

Best regards,
Bill 
bill@simplehpc.com

**Comment by XhrisPhillips** [comment] 2024-11-04 22:42
There is something more subtle going on. Hostnames are not case sensitive:

https://www.baeldung.com/linux/hostnames-case-sensitive#:~:text=Under%20Linux%2C%20the%20kernel%2C%20most,and%20packages%20employ%20case%20sensitivity.

4. Names of Hosts and Letter Case in Linux
While general adherence to POSIX is usual for UNIX, hostnames aren’t a Linux-specific concept.

In fact, there are guidelines for host naming<https://www.baeldung.com/cs/valid-characters-hostname#guidelines-for-hostnames> and the valid characters in hostnames<https://www.baeldung.com/cs/valid-characters-hostname>, as originally outlined in the RFC 952 DoD Internet Host Table Specification<https://www.rfc-editor.org/rfc/rfc952>. Critically, the latter includes a statement about letter case: No distinction is made between upper and lower case. This general consensus benefits end-users which simply use web browsers, for example.

While the above Request for Comments (RFC) from 1985 can be seen as archaic, it still holds true today in most environments, so DNS names and hostnames are case-insensitive by default.

On 5 Nov 2024, at 03:29, billchen0001 ***@***.***> wrote:



Hi Walter and Chris,
I think the hostname in Linux is case-sensitive, especially when using mpi with a machinefile in DiFX for parsing. Since we usually write the machine name to IP address resolution into the /etc/hosts file, the problem I encountered is that our machine name is R200, but vex2difx generates an mpi machinefile with r200. R200 and r200 as machine names would be considered two different machines, so I couldn't run the subsequent mpifxcorr. I have already solved this problem simply by: 1. Adding an r200 to IP address resolution to /etc/hosts, 2. Manually modifying the resolution records in xxx.machines. I can issue a PR to fix it.
I believe that DiFX itself does not involve case sensitivity issues with machine names, but MPI and Linux do distinguish between cases. Additionally, I am integrating DiFX into the HPC scheduling system, which also distinguishes between cases.

Best regards,
Bill
***@***.******@***.***>

**Comment by billchen0001** [comment] 2024-11-05 00:06
Hi Chris and Walter,
You are correct, Linux hostnames are indeed case insensitive. I re-verified that the issue is because the HPC/SLURM scheduling system is case sensitive. I might need to communicate with the scheduling system team regarding this. For now, a simple solution is to keep the machine names in lowercase to avoid problems. Additionally, since it is not case sensitive, is it possible for vex2difx not to perform case conversion? Sorry for the disturbance.
Regards,
Bill

**Comment by wumpus** [comment] 2024-11-07 05:59
It is improbable that SLURM would have this kind of bug after all these years -- you should try to reproduce the bug using a shell script. Even then it might be some SLURM addon that has the bug.

**Comment by billchen0001** [comment] 2024-11-07 08:36
I have tested and posted the question on SLURM user list and get feedback as below.

On 11/7/24 09:09, Bjørn-Helge Mevik via slurm-users wrote:
> Bill via slurm-users <[slurm-users@lists.schedmd.com](mailto:slurm-users@lists.schedmd.com)> writes:
>
>> I want to confirm that the hostname resolution is case sensitive in SLURM ?
>
> That should be easy enough to test:
>
> $ sbatch -A nn9999k -t 10 --mem-per-cpu=100 --wrap='sleep 60' --nodelist=c3-1
> Submitted batch job 13088180
> $ sbatch -A nn9999k -t 10 --mem-per-cpu=100 --wrap='sleep 60' --nodelist=C3-1
> sbatch: error: Batch job submission failed: Invalid node name specified
>
> Looks like answer is Yes. :)

Thanks for the test, Bjørn-Helge!  I can confirm with this example also
looking up a node "a001":

# scontrol show node A001,a001 | head -2
Node A001 not found
NodeName=a001 Arch=x86_64 CoresPerSocket=10

DNS can lookup this node without problems:

# host A001
a001.nifl.fysik.dtu.dk has address 10.2.129.1

Is Slurm's NodeName case sensitivity a bug or a feature?  Maybe someone
can shed light on this?

Thanks,
Ole

--

**Closed** 2024-12-01 13:19 UTC

**Comment by billchen0001** [comment] 2024-12-01 13:20
set hostname to lowercase
